### ISSUE TITLE
Add docs on how to use

### ISSUE THREAD

**Issue by rpivet** [Garethp/Vortex-Modlist-Backup#4]
It's great that this tool exists, but it doesn't serve much purpose if there isn't more information on how to use it.  Here's some starting info I was able to figure out:

After the extension is installed through Vortex, open the "Mods" list and click the "Modlist" dropdown: 
![image](https://user-images.githubusercontent.com/46726148/85931531-19c0f200-b893-11ea-9d24-9fc436a3a379.png)

From here, I have no idea what to write.  Backup what?  From what file?  Restore what?  Restore from what file?  What will restore even do?  Is it going to wipe my current mods?

**Comment by Garethp** [comment]
Great question, I'll make a note to update the description. Here's how it works:

When you create a backup, it takes the list of mods you have from NexusMods (it doesn't work with manually downloaded mods because of how the restore works) and creates a JSON file that's basically just a list of the mods and their nexus mod ID's. You select where you want to save this (I have mine backed up on Google Drive), and that's it for backing up. It doesn't back up settings, mod order or manual mods, there are probably other tools for that.

When you restore, it takes the list of mods and downloads them automatically from Nexus Mods. It won't overwrite your existing mods, just adds them. It requires Premium subscription because Vortex requires it for some reason (or did when I wrote this). It's basically the same as if you went to each individual mod page and clicked "Install with Vortex". 

The point is that you can just keep a lightweight file of tens or hundreds of kilobytes, and when you want to restore or install to a new computer it'll download those mods for you, as opposed to keeping all of those mods backed up completely with their full size.

**Comment by Dr-Tesla** [comment]
https://www.reddit.com/r/nexusmods/comments/g9kopo/vortex_extension_vortexmodlistbackup/
(complaints not from me!) I just found this, this says how to use it.

**Comment by Garethp** [comment]
That's a good explanation. To be honest, I didn't even realise other people were using this in the first place. Though if they weren't, it would probably be because of my lack of explanation

**Comment by Garethp** [comment]
I've updated the description of my mod with a How To Use. If you're interested, feel free to [check it out](https://www.nexusmods.com/site/mods/67) and let me know if it's a clear explanation. If it's not, I'll take another stab at writing it

**Comment by rpivet** [comment]
That's great @Garethp!  Thank you for addressing this issue.  The Reddit post above is helpful, I hope you're not discouraged by its poor wording after putting in the work to make this extension.  Would like to see it added to the Git Readme if the approval here is enough.

**Comment by Garethp** [comment]
No discouragement. The guy who posted it was absolutely right that I put no effort into explaining it. I seriously considered using "This God-awful extension" in the description, Yeah, I'll make sure to update the README with my next release. I'll close this issue for now, if anyone sees this and feels like more description is necessary, feel free to comment and I'll re-open
